### ISSUE TITLE
Not working with WebStorm 10.0.4

### ISSUE THREAD

**Issue by akbach** [zchee/Seti_JetBrains#16]
Internal error. Please report to https://youtrack.jetbrains.com

java.lang.ClassNotFoundException: com.intellij.ide.plugins.PluginManager
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:212)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.ide.Bootstrap.main(Bootstrap.java:36)
    at com.intellij.idea.Main.main(Main.java:83)

**Comment by zchee** [comment]
I'll check later:)

**Comment by utpalpaul** [comment]
Same issue here:

Internal error. Please report to https://youtrack.jetbrains.com
java.lang.ClassNotFoundException: com.intellij.ide.plugins.PluginManager
at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:212)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at com.intellij.ide.Bootstrap.main(Bootstrap.java:36)
at com.intellij.idea.Main.main(Main.java:83)


Also when trying to upload the icons from disk error message:

"Fail to load plugin descriptor from the file Seti_JB-icon.jar"

**Comment by bradserbu** [comment]
Ditto... +1... Thumbs Up...

**Comment by zchee** [comment]
@akbach @utpalpaul @bradserbu 
Sorry, I stayed away from the little Intellij.
but, I came back!!

I'll fix later :)

**Comment by portOdin** [comment]
Any luck on this so far? I love this plugin and would be happy to help.

**Comment by zchee** [comment]
@akbach @utpalpaul @bradserbu @portOdin
Upgraded!!
jar is move to Github Release.
See https://github.com/zchee/Seti_JetBrains/releases/tag/webstorm%2F142.4148

and, Close issue.

**Comment by utpalpaul** [comment]
I don't think its still working, below is the error log:

Internal error. Please report to https://youtrack.jetbrains.com

java.lang.NoSuchMethodError: com.intellij.util.ImageLoader.loadFromUrl(Ljava/net/URL;Z)Ljava/awt/Image;
    at com.intellij.openapi.application.impl.ApplicationInfoImpl.getProgressTailIcon(ApplicationInfoImpl.java:326)
    at com.intellij.ui.Splash.<init>(Splash.java:104)
    at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:232)
    at com.intellij.idea.IdeaApplication$IdeStarter.access$000(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:120)
    at com.intellij.idea.IdeaUltimateApplication.<init>(IdeaUltimateApplication.java:12)
    at com.intellij.idea.MainImpl$1$1.proceed(MainImpl.java:58)
    at com.intellij.ide.a.d.c$0.run(c$0.java:53)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by zchee** [comment]
@utpalpaul Hmm...
Tell me your Environment?
OS, OS Version, and more...

**Comment by utpalpaul** [comment]
OS X Yosemite
Version 10.10.5
MacBook Pro (Retina, 13-inch, Mid 2014)
Processor 2.6 GHz Intel Core i5

WebStorm 10.10.4

**Comment by mazzy89** [comment]
Still have the same error with utpalpaul

**Comment by mazzy89** [comment]
I think that could be opened again

**Comment by zchee** [comment]
@utpalpaul @mazzy89 Hmm...
I will test later :(

**Comment by zchee** [comment]
@akbach @bradserbu @portOdin @utpalpaul @mazzy89 
Do you have this problem occurs because you have installed the Seti_icon.jar?

**Comment by mazzy89** [comment]
I haven't installed Seti_icon.jar.

**Comment by utpalpaul** [comment]
I also haven't installer Seti_icon.jar.

**Comment by zchee** [comment]
@akbach @bradserbu @portOdin @utpalpaul @mazzy89 
yeeees!
Released webstorm.jar for Webstorm 10.0.4 build 141.1550.
See GitHub Release page on https://github.com/zchee/Seti_JetBrains/releases/tag/webstorm%2F141.1550

A simple download snippet,
```sh
cd /Applications/WebStorm.app/Contents/lib
mv ./webstorm.jar /tmp/
curl -LO https://github.com/zchee/Seti_JetBrains/releases/download/webstorm%2F141.1550/webstorm.jar
open /Applications/WebStorm.app
```
FYI, `webstorm.jar` is there **must be no more than two in the** `WebStorm.app/Contents/lib/`.
**Please be sure old (JetBrains original) jar is move to a directory other than lib** using the `mv` command or Finder GUI.

And, I tested on this Environment.
```sh
OS: Mac OS X El Capitan beta 8
Java: java version "1.9.0-ea"
```

Some of the errors I'm sorry :)

![screen shot 2015-09-06 at 10 28 49 pm](https://cloud.githubusercontent.com/assets/6366270/9704609/80515b1e-54e7-11e5-9dff-e692c333fbdd.png)
